### ISSUE TITLE
Frontpage: Sponsors section

### ISSUE THREAD

**Issue by leroyrosales** [hispanichackers/hispanichackersnext#21]
<img width="1390" alt="Screen Shot 2023-08-07 at 4 34 38 PM" src="https://github.com/hispanichackers/hispanichackersnext/assets/3495164/e7c55d32-6946-4937-bbe7-7f2c478dd432">

**Comment by DosLlamas** [comment]
Needs review porfis

**Comment by leroyrosales** [comment]
> Needs review porfis

Can you clarify what you need from this issue?

**Comment by DosLlamas** [comment]
Needs to be reviewed so branch can be merged in
