### ISSUE TITLE
Cleanup Items

### ISSUE THREAD

**Issue by drebarrera** [hispanichackers/hispanichackersnext#40]
- Switch block links to arrow links
- Transparent header on init
- Change up promo world image to something more friendly
- Borders in the hero component - change from 8px to 4px on mutual borders

**Comment by drebarrera** [comment]
- Make header sticky
- Make footer non-sticky (relative)

**Comment by leroyrosales** [comment]
All these issues have been separated out into their own tickets now, closing this.
