### ISSUE TITLE
Bug: Broken nav styling

### ISSUE THREAD

**Issue by leroyrosales** [hispanichackers/hispanichackersnext#43]
A merged in change makes the nav links invisible now in dev: https://hispanichackersnext-git-develop-hispanichackers.vercel.app/

We'll need to re-implement style changes or find a fix.

**Comment by DosLlamas** [comment]
-Change Contact US buttons to arrows like we have on front page 
-Add links to the sponsor's pages so user can click
-Also change the background of sponsors section to white so the logos look better

**Comment by leroyrosales** [comment]
@DosLlamas did you mean to add these notes to #21 ?
